# https://help.github.com/en/articles/workflow-syntax-for-github-actions

name: Build

on: [push]

jobs:
  build-mac:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install nim
      run: brew install nim
    - name: nimble build
      run: nimble build -d:release -y
    - name: Upload artifact # https://help.github.com/en/articles/persisting-workflow-data-using-artifacts
      uses: actions/upload-artifact@v1
      with:
        name: yaml2json-Darwin-x86_64
        path: yaml2json

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build yaml2json-builder
        run: docker build -f build/Dockerfile -t yaml2json-builder .
      - name: nimble build
        run: docker run -v ${GITHUB_WORKSPACE}:${GITHUB_WORKSPACE} -w ${GITHUB_WORKSPACE} yaml2json-builder nimble build -d:release -os:linux -cpu:amd64 -cpu:arm -y
      - name: Upload artifact # https://help.github.com/en/articles/persisting-workflow-data-using-artifacts
        uses: actions/upload-artifact@v1
        with:
          name: yaml2json-Linux-x86_64
          path: yaml2json
