# https://help.github.com/en/articles/workflow-syntax-for-github-actions

name: Build

on: [push]

jobs:
  build-macos-amd64:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install nim
      run: brew install nim
    - name: nimble build
      run: nimble build -d:release --os:MacOSX --cpu:amd64 -y
    - name: Create archive directory
      run: |
        mkdir yaml2json
        cp yaml2json README.md NOTICE yaml2json/
    - name: Upload artifact # https://help.github.com/en/articles/persisting-workflow-data-using-artifacts
      uses: actions/upload-artifact@v1
      with:
        name: yaml2json-Darwin-x86_64
        path: yaml2json

  build-linux-amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: nimble build
        uses: docker://nimlang/nim
        with:
          entrypoint: /bin/nimble
          args: build -d:release --os:linux --cpu:amd64 -y
      - name: Create archive directory
        run: |
          mkdir yaml2json
          cp yaml2json README.md NOTICE yaml2json/
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: yaml2json-Linux-x86_64
          path: yaml2json

  build-linux-arm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: nimble build
        uses: docker://nonylene/nim-crosscompile
        with:
          entrypoint: /bin/nimble
          args: build -d:release --os:linux --cpu:arm -y
      - name: Create archive directory
        run: |
          mkdir yaml2json
          cp yaml2json README.md NOTICE yaml2json/
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: yaml2json-Linux-armv7l
          path: yaml2json

  create-release:
   # if: startsWith(github.ref, 'refs/tags/v')
    needs: [build-macos-amd64, build-linux-amd64, build-linux-arm]
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create-release
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}

      - uses: actions/download-artifact@v1
        with:
          name: yaml2json-Darwin-x86_64
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./yaml2json-Darwin-x86_64.zip
          asset_name: yaml2json-Darwin-x86_64.zip
          asset_content_type: application/zip

      - uses: actions/download-artifact@v1
        with:
          name: yaml2json-Linux-x86_64
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./yaml2json-Linux-x86_64.zip
          asset_name: yaml2json-Linux-x86_64.zip
          asset_content_type: application/zip

      - uses: actions/download-artifact@v1
        with:
          name: yaml2json-Linux-armv7l
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./yaml2json-Linux-armv7l.zip
          asset_name: yaml2json-Linux-armv7l.zip
          asset_content_type: application/zip
